# This workflow runs linters and formatters

name: Lint and Format

on: push

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Pyright
      # Note: npm is already installed because it's included in the GH Actions imate
      run: |
        npm install -g pyright

    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v9

    - name: Install library and dependencies
      run: |
        poetry run pip install --upgrade pip setuptools
        poetry install --no-interaction

    - name: Check pyproject.toml with Poetry
      run: |
        poetry check --strict

    - name: Lint and Format with Ruff
      run: |
        poetry run ruff format --diff
        poetry run ruff check

    - name: Check Types with Mypy
      run: |
        poetry run mypy -p multicast_expert

    - name: Check Docs with Docsig
      run: |
        poetry run docsig multicast_expert

    - name: Lint with Pyright
      run: |
        poetry run pyright