name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Install project
        run: poetry install --no-interaction
      - name: Configure IP routes # See "Development Setup.md"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo ip -6 route add table local ff11::/16 dev lo
      - name: Run Pytest
        run: poetry run pytest

  my-py:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9
      - name: Install project
        run: poetry install --no-interaction
      - name: Run Mypy
        run: poetry run mypy -p multicast_expert
